---
convertion:
  conda_env: "cd"
  input_dirs:
    - "/lustre/home/hacosta/Open-Data/Processed/root/fondo"
    - "/lustre/home/hacosta/Open-Data/Processed/root/senal"
  tree_name: "Events"
  
  branches:
      - "run"
      - "event"
      - "luminosityBlock"
      - "MET_pt"
      - "MET_phi"
      - "Dataset_ID"
      - "HLT_Ele32_WPTight_Gsf"
      - "HLT_Mu50"
      - "HLTMU50"
      - "HLTEle32"
      - "3Lep_pass"
      - "Z_pass"
      - "W_pass"
      - "nLeptons"
      - "A_pass"
      - "A_Wpass"
      - "A_nlep"
      - "A_Zmass"
      - "A_Wmass"
      - "A_ptZ"
      - "A_Dr_Z"
      - "A_Dphi_Z"
      - "A_Deta_Z"
      - "A_Sum_pt"
      - "A_Sum_mass"
      - "A_Lep1Z_pt"
      - "A_Lep1Z_eta"
      - "A_Lep1Z_phi"
      - "A_Lep2Z_pt"
      - "A_Lep2Z_eta"
      - "A_Lep2Z_phi"
      - "A_Lep3W_pt"
      - "A_Lep3W_eta"
      - "A_Lep3W_phi"
      - "B_pass"
      - "B_Wpass"
      - "B_nlep"
      - "B_Zmass"
      - "B_Wmass"
      - "B_ptZ"
      - "B_Dr_Z"
      - "B_Dphi_Z"
      - "B_Deta_Z"
      - "B_Sum_pt"
      - "B_Sum_mass"
      - "B_mu1ip3d"
      - "B_Lep1Z_pt"
      - "B_Lep1Z_eta"
      - "B_Lep1Z_phi"
      - "B_Lep2Z_pt"
      - "B_Lep2Z_eta"
      - "B_Lep2Z_phi"
      - "B_Lep3W_pt"
      - "B_Lep3W_eta"
      - "B_Lep3W_phi"
      - "C_pass"
      - "C_Wpass"
      - "C_nlep"
      - "C_Zmass"
      - "C_Wmass"
      - "C_ptZ"
      - "C_Dr_Z"
      - "C_Dphi_Z"
      - "C_Deta_Z"
      - "C_Sum_pt"
      - "C_Sum_mass"
      - "C_mu1ip3d"
      - "C_mu2ip3d"
      - "C_Lep1Z_pt"
      - "C_Lep1Z_eta"
      - "C_Lep1Z_phi"
      - "C_Lep2Z_pt"
      - "C_Lep2Z_eta"
      - "C_Lep2Z_phi"
      - "C_Lep3W_pt"
      - "C_Lep3W_eta"
      - "C_Lep3W_phi"
      - "D_pass"
      - "D_Wpass"
      - "D_nlep"
      - "D_Zmass"
      - "D_Wmass"
      - "D_ptZ"
      - "D_Dr_Z"
      - "D_Dphi_Z"
      - "D_Deta_Z"
      - "D_Sum_pt"
      - "D_Sum_mass"
      - "D_mu1ip3d"
      - "D_mu2ip3d"
      - "D_mu3ip3d"
      - "D_Lep1Z_pt"
      - "D_Lep1Z_eta"
      - "D_Lep1Z_phi"
      - "D_Lep2Z_pt"
      - "D_Lep2Z_eta"
      - "D_Lep2Z_phi"
      - "D_Lep3W_pt"
      - "D_Lep3W_eta"
      - "D_Lep3W_phi"

      # If you do not have jagged arrays leave it as null. If you use, the default value is 10
  max_jagged_len: null
  
  eos_output_dir: "/lustre/home/hacosta/Open-Data/Processed/h5"
slurm_params:
  executable_file: "run_conversion.sh"
  cpus: 1
  gpus: 0
  mem: "1500M"
  time: "00:20:00"
  partition: "cpu" 
